//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Клиент.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Data.DataSet GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FillFIO", ReplyAction="http://tempuri.org/IService1/FillFIOResponse")]
        System.Data.DataSet FillFIO();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FillFIO", ReplyAction="http://tempuri.org/IService1/FillFIOResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FillFIOAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FillAvto", ReplyAction="http://tempuri.org/IService1/FillAvtoResponse")]
        System.Data.DataSet FillAvto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FillAvto", ReplyAction="http://tempuri.org/IService1/FillAvtoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> FillAvtoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NewRec", ReplyAction="http://tempuri.org/IService1/NewRecResponse")]
        void NewRec(string ID_OBORYD, string ID_VID_RABOT, string Data_polychen, string Data_vipolnen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NewRec", ReplyAction="http://tempuri.org/IService1/NewRecResponse")]
        System.Threading.Tasks.Task NewRecAsync(string ID_OBORYD, string ID_VID_RABOT, string Data_polychen, string Data_vipolnen);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Клиент.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Клиент.ServiceReference1.IService1>, Клиент.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
        
        public System.Data.DataSet FillFIO() {
            return base.Channel.FillFIO();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FillFIOAsync() {
            return base.Channel.FillFIOAsync();
        }
        
        public System.Data.DataSet FillAvto() {
            return base.Channel.FillAvto();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FillAvtoAsync() {
            return base.Channel.FillAvtoAsync();
        }
        
        public void NewRec(string ID_OBORYD, string ID_VID_RABOT, string Data_polychen, string Data_vipolnen) {
            base.Channel.NewRec(ID_OBORYD, ID_VID_RABOT, Data_polychen, Data_vipolnen);
        }
        
        public System.Threading.Tasks.Task NewRecAsync(string ID_OBORYD, string ID_VID_RABOT, string Data_polychen, string Data_vipolnen) {
            return base.Channel.NewRecAsync(ID_OBORYD, ID_VID_RABOT, Data_polychen, Data_vipolnen);
        }
    }
}
